import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './component/Navbar/Navbar'
import Footer from './component/Footer/Footer'
import { CartProvider } from './context/CartContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        
      <body ><CartProvider><Navbar/> {children}
      
      </CartProvider>
      <Footer/>
      </body>
    </html>
  )
}
