import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './component/Navbar/Navbar'
import Footer from './component/Footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        
      <body ><Navbar/>{children}
      {/* <Footer/> */}
      </body>
    </html>
  )
}
